// ============================================================
// Color Art Munich — Paintings Data
// sold: true = shows "Verkauft", price: 0 = "Preis auf Anfrage"
// ============================================================

const paintings = [
  { img: "0001.jpg", title: "Horizon",                   price: 950,  sold: true,  material: "Acryl, Leinwand", size: "160x60x1,5 cm" },
  { img: "0002.jpg", title: "The Blue Pearl",            price: 1050, sold: false, material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0003.jpg", title: "Evening Green",             price: 999,  sold: false, material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0004.jpg", title: "Dance of Words",            price: 750,  sold: false, material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0005.jpg", title: "Echoes of Venice",          price: 950,  sold: false, material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0006.jpg", title: "Ashes of Gold",             price: 850,  sold: true, material: "Acryl, Leinwand", size: "90x120x1,5 cm" },
  { img: "0007.jpg", title: "Horizon Line",              price: 1100, sold: false, material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0008.jpg", title: "The Earth Dreams",          price: 800,  sold: false, material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0009.jpg", title: "Flame and Sky Tower",       price: 850,  sold: true,  material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0010.jpg", title: "Stillness Has a Name",      price: 800,  sold: false, material: "Acryl, Leinwand", size: "90x120x1,5 cm" },
  { img: "0011.jpg", title: "Scar of Silence",           price: 750,  sold: false, material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0012.jpg", title: "The Gallop and the Glide",  price: 800,  sold: false, material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0013.jpg", title: "Ship of the Lost",          price: 900,  sold: false, material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0014.jpg", title: "Earth & Sea Harmony",       price: 850,  sold: true,  material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0015.jpg", title: "Oxidized Reverie",          price: 900,  sold: false, material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0016.jpg", title: "Midnight Gilded Dreams",    price: 850,  sold: false, material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0017.jpg", title: "Hich",                      price: 850,  sold: false, material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0018.jpg", title: "Luminous Firework Fusion",  price: 900,  sold: false, material: "Acryl, Leinwand", size: "100x100x2 cm" },
  { img: "0019.jpg", title: "Golden Green Harmony",      price: 550,  sold: false, material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0020.jpg", title: "Midnight Gold Symphony",    price: 350,  sold: false, material: "Acryl, Leinwand", size: "50x40x1,5 cm" },
  { img: "0021.jpg", title: "Amethyst Shadows",          price: 350,  sold: false, material: "Acryl, Leinwand", size: "30x40x1,5 cm" },
  { img: "0022.jpg", title: "Blue-Green Mirage",         price: 800,  sold: true,  material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0023.jpg", title: "Bronze Serenity",           price: 750,  sold: false, material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0024.jpg", title: "Silver Eclipse",            price: 550,  sold: false, material: "Acryl, Leinwand", size: "60x80x2 cm" },
  { img: "0025.jpg", title: "Verdant Reflections",       price: 550,  sold: false, material: "Acryl, Leinwand", size: "80x60x2 cm" },
  { img: "0026.jpg", title: "Bronze Ripple",             price: 550,  sold: false, material: "Acryl, Leinwand", size: "80x60x2 cm" },
  { img: "0027.jpg", title: "Violet Vines",              price: 750,  sold: false, material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0028.jpg", title: "B Mim: The Fire of Nature", price: 750,  sold: false, material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0029.jpg", title: "Woodland Shades",           price: 750,  sold: false, material: "Acryl, Leinwand", size: "100x100x4 cm" },
  { img: "0030.jpg", title: "Rosy Radiance",             price: 900,  sold: false, material: "Acryl, Leinwand", size: "120x80x2,5 cm" },
  { img: "0031.jpg", title: "Rainbow Sweep",             price: 550,  sold: false, material: "Acryl, Leinwand", size: "60x80x2 cm" },
  { img: "0032.jpg", title: "Goldfire Strokes",          price: 600,  sold: false, material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0033.jpg", title: "Gold Flecked Shadow",       price: 550,  sold: false, material: "Acryl, Leinwand", size: "60x80x2 cm" },
  { img: "0034.jpg", title: "Seafoam Brilliance",        price: 1500, sold: false, material: "Acryl, Leinwand", size: "120x80x2,5 cm" },
  { img: "0035.jpg", title: "Black Cherry Shine",        price: 1500, sold: false, material: "Acryl, Leinwand", size: "120x80x2,5 cm" },
  { img: "0036.jpg", title: "Steel Green Radiance",      price: 1500, sold: false, material: "Acryl, Leinwand", size: "120x80x2,5 cm" },
  { img: "0037.jpg", title: "Lavender Skies",            price: 550,  sold: false, material: "Acryl, Leinwand", size: "50x70x2 cm" },
  { img: "0038.jpg", title: "Polished Walnut",           price: 750,  sold: false, material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0039.jpg", title: "Leafy Gold",                price: 750,  sold: false, material: "Acryl, Leinwand", size: "100x100x2 cm" },
  { img: "0040.jpg", title: "Blue Noir Blaze",           price: 800,  sold: false, material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0041.jpg", title: "Pink Wave",                 price: 600,  sold: false, material: "Acryl, Leinwand", size: "80x60x2 cm" },
  { img: "0042.jpg", title: "Rainbow Eclipse",           price: 750,  sold: false, material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0043.jpg", title: "Graphite Glow",             price: 750,  sold: false, material: "Acryl, Leinwand", size: "70x120x1,5 cm" },
  { img: "0044.jpg", title: "Rust and Steel",            price: 750,  sold: false, material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0045.jpg", title: "Sky and Snow",              price: 850,  sold: false, material: "Acryl, Leinwand", size: "100x100x4 cm" },
  { img: "0046.jpg", title: "Twilight Grove",            price: 750,  sold: false, material: "Acryl, Leinwand", size: "70x100x1,5 cm" },
  { img: "0047.jpg", title: "Midnight Moss",             price: 650,  sold: false, material: "Acryl, Leinwand", size: "60x80x1,5 cm" },
  { img: "0048.jpg", title: "Mango Bliss",               price: 600,  sold: true,  material: "Acryl, Leinwand", size: "60x80x2 cm" },
  { img: "0049.jpg", title: "House in Flame",            price: 900,  sold: true,  material: "Acryl, Leinwand", size: "120x90x1,5 cm" },
  { img: "0050.jpg", title: "The Infinite Run",          price: 850,  sold: true,  material: "Acryl, Leinwand", size: "90x120x1,5 cm" },
  { img: "0051.jpg", title: "Hich: The Sacred Absence",  price: 850,  sold: true,  material: "Acryl, Leinwand", size: "120x80x1,5 cm" },
  { img: "0052.jpg", title: "Golden Silence",            price: 870,  sold: true,  material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0053.jpg", title: "Aquatic Dance of Time",     price: 1150, sold: true,  material: "Acryl, Leinwand", size: "180x60x1,5 cm" },
  { img: "0054.jpg", title: "Between Night and Deep",    price: 850,  sold: true,  material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0055.jpg", title: "Golden Bloom Inferno",      price: 850,  sold: true,  material: "Acryl, Leinwand", size: "120x80x1,5 cm" },
  { img: "0056.jpg", title: "Esgh",                      price: 800,  sold: true,  material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0057.jpg", title: "Flight of Freedom",         price: 870,  sold: true,  material: "Acryl, Leinwand", size: "70x100x1,5 cm" },
  { img: "0058.jpg", title: "Mind's Mirage",             price: 850,  sold: true,  material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0059.jpg", title: "Zara Golden",               price: 760,  sold: false, material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0060.jpg", title: "Rainbow Dream",             price: 650,  sold: true,  material: "Acryl, Leinwand", size: "60x80x2 cm" },
  { img: "0061.jpg", title: "Mistress of the Grey",      price: 850,  sold: true,  material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0062.jpg", title: "Shimmering Gold Spots",     price: 650,  sold: true,  material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0063.jpg", title: "Rose-Gold Blossoms",        price: 800,  sold: true,  material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0064.jpg", title: "Forest Gold Dust",          price: 850,  sold: true,  material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0065.jpg", title: "Golden Horizon",            price: 850,  sold: true,  material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0066.jpg", title: "Golden Horse",              price: 800,  sold: true,  material: "Acryl, Leinwand", size: "70x100x1,5 cm" },
  { img: "0067.jpg", title: "Sunset Soul",               price: 550,  sold: true,  material: "Acryl, Leinwand", size: "60x80x2 cm" },
  { img: "0068.jpg", title: "Pink Aurora Florals",       price: 850,  sold: true,  material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0069.jpg", title: "Shimmering Love",           price: 850,  sold: true,  material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0070.jpg", title: "Royal Blue and Gold",       price: 950,  sold: true,  material: "Acryl, Leinwand", size: "100x100x4 cm" },
  { img: "0071.jpg", title: "Golden Ember",              price: 750,  sold: true,  material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0072.jpg", title: "Eshgh of the Sun",          price: 850,  sold: true,  material: "Acryl, Leinwand", size: "70x120x1,5 cm" },
  { img: "0073.jpg", title: "Blue Velvet Gleam",         price: 750,  sold: true,  material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0074.jpg", title: "Golden Light Windows",      price: 850,  sold: true,  material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0075.jpg", title: "Lava Burst",                price: 950,  sold: true,  material: "Acryl, Leinwand", size: "120x80x2 cm" },
  { img: "0076.jpg", title: "Striped Harmony",           price: 850,  sold: true,  material: "Acryl, Leinwand", size: "100x100x4 cm" },
  { img: "0077.jpg", title: "Eshgh's Sapphire Dream",    price: 800,  sold: true,  material: "Acryl, Leinwand", size: "80x120x1,5 cm" },
  { img: "0078.jpg", title: "Nature's Wave",             price: 650,  sold: true,  material: "Acryl, Leinwand", size: "60x80x2 cm" },
  { img: "0079.jpg", title: "Colorful Orbs",             price: 700,  sold: true,  material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0080.jpg", title: "Stained Glass Shadows",     price: 850,  sold: true,  material: "Acryl, Leinwand", size: "80x100x1,5 cm" },
  { img: "0081.jpg", title: "Gold Leaf Surge",           price: 400,  sold: true,  material: "Acryl, Leinwand", size: "40x50x2 cm" },
  { img: "0082.jpg", title: "Scarlet Steel",             price: 750,  sold: true,  material: "Acryl, Leinwand", size: "80x100x2 cm" },
  { img: "0083.jpg", title: "Golden Sandstone",          price: 400,  sold: true,  material: "Acryl, Leinwand", size: "40x50x2 cm" },
  { img: "0084.jpg", title: "Scarlet Blossom",           price: 400,  sold: true,  material: "Acryl, Leinwand", size: "40x50x1,5 cm" },
  { img: "0085.jpg", title: "Dream Parade",           	 price: 950,  sold: false,  material: "Acryl, Leinwand", size: "160x60x1,5 cm" },
  { img: "0086.jpg", title: "Between Worlds",            price: 750,  sold: false,  material: "Acryl, Leinwand", size: "120x80x1,5 cm" },
  { img: "0087.jpg", title: "Beneath the Surface",       price: 850,  sold: false,  material: "Acryl, Leinwand", size: "100x100x1,5 cm" },
  { img: "0088.jpg", title: "The Origin",        		 price: 700,  sold: false,  material: "Acryl, Leinwand", size: "120x80x1,5 cm" },
];
